<?php

declare(strict_types=1);

namespace Mpc\MpCore\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use TYPO3\CMS\Core\Cache\Frontend\FrontendInterface;
use TYPO3\CMS\Core\Http\HtmlResponse;
use TYPO3\CMS\Core\Site\Entity\Site;

/**
 * Serves a dynamic robots.txt with sitemap reference and optional AI-crawler rules.
 */
final class RobotsTxtMiddleware implements MiddlewareInterface
{
    use GeoTextFileMiddlewareTrait;

    public function __construct(
        private readonly FrontendInterface $cache,
    ) {}

    /**
     * Default crawl rules for the generic `User-agent: *` group. Keeps the TYPO3
     * backend, source, temp/derivative files and parameterized duplicate URLs out
     * of search indexes while allowing public frontend assets shipped from
     * sysext/frontend.
     *
     * @var list<string>
     */
    private const DEFAULT_RULES = [
        'Disallow: /typo3/',
        'Disallow: /typo3_src/',
        'Disallow: /typo3temp/',
        'Disallow: /fileadmin/_processed_/',
        'Disallow: /*?cHash=',
        'Disallow: /*?tx_',
        'Allow: /typo3/sysext/frontend/Resources/Public/*',
    ];

    /**
     * Common AI / generative search crawlers (training + retrieval).
     *
     * @var list<string>
     */
    private const AI_CRAWLERS = [
        'GPTBot',
        'OAI-SearchBot',
        'ChatGPT-User',
        'ClaudeBot',
        'anthropic-ai',
        'PerplexityBot',
        'Google-Extended',
        'CCBot',
        'Applebot-Extended',
    ];

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $site = $request->getAttribute('site');
        if (!$site instanceof Site || !$this->matchesSitePath($request, $site, 'robots.txt')) {
            return $handler->handle($request);
        }

        if (!$this->isTruthySiteSetting($site, 'seo.robots.enabled', true)) {
            return $handler->handle($request);
        }

        $language = $this->resolveSiteLanguage($request, $site);
        $cacheIdentifier = $this->geoTextCacheIdentifier('robots', $site, $language);

        $content = $this->cache->get($cacheIdentifier);
        if (!is_string($content)) {
            $content = $this->buildRobotsTxt($site);
            $this->cache->set(
                $cacheIdentifier,
                $content,
                $this->geoTextCacheTags($site),
                self::GEO_TEXT_CACHE_LIFETIME
            );
        }

        return new HtmlResponse($content, 200, [
            'Content-Type' => 'text/plain; charset=utf-8',
        ]);
    }

    private function buildRobotsTxt(Site $site): string
    {
        $lines = [
            '# robots.txt for ' . $this->resolveSiteName($site),
            '# Generated by mp_core (RobotsTxtMiddleware)',
            '',
            'User-agent: *',
            'Allow: /',
        ];

        foreach (self::DEFAULT_RULES as $rule) {
            $lines[] = $rule;
        }

        $crawlDelay = (int)$this->resolveSiteSetting($site, 'seo.robots.crawlDelay', 0);
        if ($crawlDelay > 0) {
            $lines[] = 'Crawl-delay: ' . $crawlDelay;
        }

        $lines[] = '';

        if (!$this->isTruthySiteSetting($site, 'seo.robots.allowAiBots', true)) {
            foreach (self::AI_CRAWLERS as $bot) {
                $lines[] = 'User-agent: ' . $bot;
                $lines[] = 'Disallow: /';
                $lines[] = '';
            }
        }

        foreach ($this->resolveSitemapUrls($site) as $sitemapUrl) {
            $lines[] = 'Sitemap: ' . $sitemapUrl;
        }

        $additional = trim((string)$this->resolveSiteSetting($site, 'seo.robots.additional', ''));
        if ($additional !== '') {
            $lines[] = '';
            $lines[] = rtrim($additional, "\r\n");
        }

        return rtrim(implode("\n", $lines)) . "\n";
    }

    /**
     * One sitemap-index URL per enabled site language. EXT:seo generates a
     * separate per-language sitemap under each language base (e.g. `/sitemap.xml`
     * and `/en/sitemap.xml`), so all of them must be advertised from the single
     * root robots.txt for every language to be discoverable.
     *
     * @return list<string>
     */
    private function resolveSitemapUrls(Site $site): array
    {
        $urls = [];
        foreach ($site->getLanguages() as $language) {
            $urls[] = rtrim((string)$language->getBase(), '/') . '/sitemap.xml';
        }

        if ($urls === []) {
            $urls[] = $this->resolveSiteBaseUrl($site) . '/sitemap.xml';
        }

        return array_values(array_unique($urls));
    }

    /**
     * Human-readable site name for the header comment, taken from the site
     * configuration `websiteTitle` with the base URL host as a fallback.
     */
    private function resolveSiteName(Site $site): string
    {
        $name = trim((string)($site->getConfiguration()['websiteTitle'] ?? ''));
        if ($name === '') {
            $name = $site->getBase()->getHost();
        }

        return $name;
    }
}
